behaviors:
  3DBall:
    trainer: sac
    batch_size: 64
    buffer_size: 12000
    buffer_init_steps: 0
    hidden_units: 64
    init_entcoef: 0.5
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 5.0e5
    memory_size: 128
    normalize: true
    steps_per_update: 10
    num_layers: 2
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 12000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
