behaviors:
  CrawlerStatic:
    trainer: sac
    batch_size: 256
    buffer_size: 500000
    buffer_init_steps: 2000
    hidden_units: 512
    init_entcoef: 1.0
    learning_rate: 0.0003
    learning_rate_schedule: constant
    max_steps: 3e6
    memory_size: 128
    normalize: true
    steps_per_update: 20
    num_layers: 3
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 30000
    tau: 0.005
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.995
