behaviors:
  3DBallHard:
    trainer: ppo
    batch_size: 1200
    beta: 0.001
    buffer_size: 12000
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 5.0e6
    memory_size: 128
    normalize: true
    num_epoch: 3
    num_layers: 2
    time_horizon: 1000
    sequence_length: 64
    summary_freq: 12000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.995
