behaviors:
  BigWallJump:
    trainer: ppo
    batch_size: 128
    beta: 0.005
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 2e7
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 20000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

  SmallWallJump:
    trainer: ppo
    batch_size: 128
    beta: 0.005
    buffer_size: 2048
    epsilon: 0.2
    hidden_units: 256
    lambd: 0.95
    learning_rate: 0.0003
    learning_rate_schedule: linear
    max_steps: 5e6
    memory_size: 128
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 128
    sequence_length: 64
    summary_freq: 20000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
